<a href="https://colab.research.google.com/github/chandumonubol/python/blob/main/Encoding15_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 0,1,4324 -- these can be easily understood by any machine

# "apple", "mango", "blue" -- machine learning algorithms do not understand the words
# they will raise an error and you will not be able to create a model

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame({'cust_id':[101,102,103,104,105],
                   'age':[21,24,25,21,24],
                   "gender":["male",'female','male','female','female'],
                   "ratings":['excellent','good','average','average','good']})

In [ ]:
# The process of conversion of text into numbers is called as Encoding

In [ ]:
# Numerical Data -- which is quantitative data, which consists of numbers and numeric values

In [ ]:
# Categorical Data -- categories or groups will exists

#Two types:

# 1. Nominal Data

# no order exists

# color - red, blue, green, yellow, pink, orange
#         blue, red, green, pink, yellow

# cities - delhi, pune, blr, mumbai

# names, fruits, cars, flowers, bikes, ac, brands, animals, phones, veggies
# 2. Ordinal Data
# There is some order

# Customer satisfaction
# Excellent, good, average, poor, very poor

# education degrees
# school, graduation, pg, phd

# age, ranks, feedback, classes, perfomance of employee or students, salary, income slabs

In [ ]:
#Types of encoding for each types of data

#ordinal data - ordinal encoding

#nominal data - one hot encoding, label encoding

Label Encoding

In [ ]:
color = pd.DataFrame({'S.no.':[1,2,3,4,5],
                       'colors':['red','green','red','red','green']})

In [ ]:
colors

   S.no. colors
0      1    red
1      2  green
2      3    red
3      4    red
4      5  green

In [ ]:
#how many catagories--2--red and green, nominal data
#JUST LIKE INDEXING STARTS WITH 0 BY DEFAULT ENCODING WILL ALSO START FROM 0

In [ ]:
from sklearn.preprocessing import LabelEncoder

# sklearn -- library
# preprocessing -- module
# LabelEncoder -- class

le = LabelEncoder() # object of the class so you can use the methods of the class
# le - object of class LabelEncoder

In [ ]:
color['colors'] = le.fit_transform(color['colors'])
#dataframe name[column name]=object.method

In [ ]:
color

   S.no.  colors
0      1       1
1      2       0
2      3       1
3      4       1
4      5       0

In [ ]:
# fit_transform will read the input values and will replace them with numeric values

# red - 1
# green - 0

# chronological order -- as per the order of abcd -- g comes first so therefore it gets the value 0
# Then comes r so red gets the value 1

In [ ]:
color = pd.DataFrame({'S.no.':[1,2,3,4,5, 6, 7, 8, 9, 10],
                       'colors':['red','green','red','red','green', "blue","pink","blue","pink", 'red']})

In [ ]:
color['colors']=le.fit_transform(color['colors'])

In [ ]:
color

   S.no.  colors
0      1       3
1      2       1
2      3       3
3      4       3
4      5       1
5      6       0
6      7       2
7      8       0
8      9       2
9     10       3

In [ ]:
df

   cust_id  age  gender    ratings
0      101   21    male  excellent
1      102   24  female       good
2      103   25    male    average
3      104   21  female    average
4      105   24  female       good

One hot encoding

In [ ]:
pd.get_dummies(df, columns =['gender'])

   cust_id  age    ratings  gender_female  gender_male
0      101   21  excellent          False         True
1      102   24       good           True        False
2      103   25    average          False         True
3      104   21    average           True        False
4      105   24       good           True        False

In [ ]:
pd.get_dummies(df, columns =['gender','ratings'])

,cust_id,age,gender_female,gender_male,ratings_average,ratings_excellent,ratings_good
0,101,21,False,True,False,True,False
1,102,24,True,False,False,False,True
2,103,25,False,True,True,False,False
3,104,21,True,False,True,False,False
4,105,24,True,False,False,False,True

In [ ]:
pd.get_dummies(color, columns =['colors'])

   S.no.  colors_0  colors_1  colors_2  colors_3
0      1     False     False     False      True
1      2     False      True     False     False
2      3     False     False     False      True
3      4     False     False     False      True
4      5     False      True     False     False
5      6      True     False     False     False
6      7     False     False      True     False
7      8      True     False     False     False
8      9     False     False      True     False
9     10     False     False     False      True

In [ ]:
# curse of dimensionality

# if too many categories are too many columns will be created
# which will result in more memory, less speed, high complexity

In [ ]:
car= pd.DataFrame({'Cust_name':['A','B','C','D','A'],
                       'cars':['hONDA','Audi','BMW','BMW','Audi']})

In [ ]:
car['cars']=le.fit_transform(car['cars'])

In [ ]:
car

  Cust_name  cars
0         A     2
1         B     0
2         C     1
3         D     1
4         A     0

In [ ]:
pd.get_dummies(car, columns =['cars'])

  Cust_name  cars_0  cars_1  cars_2
0         A   False   False    True
1         B    True   False   False
2         C   False    True   False
3         D   False    True   False
4         A    True   False   False

In [ ]:
import pandas as pd

Ordinal Encoding

In [ ]:
edu = pd.DataFrame({'education':["School","Grad","PG","PHd","School","PG","Grad","Grad",'PG']})

In [ ]:
edu

  eudcation
0    School
1      Grad
2        PG
3       PHd
4    School
5        PG
6      Grad
7      Grad
8        PG

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
encoder= OrdinalEncoder(categories=[["School","Grad","PG","PHd"]])
# encoder =  OrdinalEncoder(categories=["School", "Grad","PG",'PHd'])

In [ ]:
edu[['education']] = encoder.fit_transform(edu[['education']])

In [ ]:
df = pd.DataFrame({'cust_id':[101,102,103,104,105],
                   'age':[21,24,25,21,24],
                   "gender":["male",'female','male','female','female'],
                   "ratings":['excellent','good','average','average','good']})

In [ ]:
encoder1= OrdinalEncoder(categories=[['average','good','excellent']])

In [ ]:
df[['ratings']] = encoder1.fit_transform(df[['ratings']])

In [ ]:
df

   cust_id  age  gender  ratings
0      101   21    male      2.0
1      102   24  female      1.0
2      103   25    male      0.0
3      104   21  female      0.0
4      105   24  female      1.0

In [ ]:
encoder2= OrdinalEncoder(categories=[['hONDA','Audi','BMW']])

In [ ]:
car['cars']=encoder2.fit_transform(car[['cars']])

In [ ]:
car

  Cust_name  cars
0         A   0.0
1         B   1.0
2         C   2.0
3         D   2.0
4         A   1.0

Difference

lablel=alphabetical

one-hot= creates another columns for each catagories

ordinal= we define the order of the catagories